# Generated by Django 5.1.2 on 2024-11-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_options_alter_eventtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.event')),
                ('participant_count', models.IntegerField()),
                ('task', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
