# Generated by Django 5.1.2 on 2024-11-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_eventdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='participant_count',
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_type', to='api.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_detail', serialize=False, to='api.event'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
