# Generated by Django 5.1.2 on 2024-11-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_event_image_event_image_url_eventimage_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
    ]
